name: ci

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - uses: foundry-rs/foundry-toolchain@v1
      - run: bun run generate
      - run: test -z "$(git status --porcelain)"
      - run: bun run biome ci
  contracts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./contracts
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@v1
      - run: forge fmt --check
      - run: forge test -vvv
